import type { FullGameTrainingTask } from '../types';

/**
 * ONE EIGHT 一局指南 — 考えて指す Black 番
 * Full game scripted Training: 22 moves, Black perspective.
 *
 * Phase 1: データ定義 + 検算test用。UI未実装・一覧未登録。
 */
export const FULL_GAME_V1: FullGameTrainingTask = {
  id: 'full-game-v1',
  title: 'ONE EIGHT 一局指南 — 考えて指す Black 番',
  description: '黒番として一局を通して考えながら指す実戦形式のTraining。',
  perspective: 'black',
  steps: [
    {
      moveNumber: 1,
      player: 'black',
      kind: 'user',
      move: { position: 'E', buildType: 'massive', gates: [6] },
      learningPoint: '中央ポジションEに着手し、Gate 6をMassiveで占有する。',
      shortPrompt: 'EにMassive(Gate 6)を指してください。',
      expectedMove: { position: 'E', buildType: 'massive', gates: [6] },
      explanation: '中央のEはGate 6を通じて複数ポジションに影響を与える要所。序盤にMassiveで大型アセットを配置し主導権を握る。',
    },
    {
      moveNumber: 2,
      player: 'white',
      kind: 'auto',
      move: { position: 'H', buildType: 'massive', gates: [9] },
      learningPoint: 'WhiteがHにMassive(Gate 9)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'H', buildType: 'massive', gates: [9] },
      explanation: 'WhiteはHに着手してGate 9を確保する。',
    },
    {
      moveNumber: 3,
      player: 'black',
      kind: 'user',
      move: { position: 'A', buildType: 'quad', gates: [1, 2, 7, 12] },
      learningPoint: 'AをQuadで4Gate全て占有する。',
      shortPrompt: 'AにQuad(Gate 1,2,7,12)を指してください。',
      expectedMove: { position: 'A', buildType: 'quad', gates: [1, 2, 7, 12] },
      explanation: 'PositionAはGate 1,2,7,12に接続。Quadで4Gate全体に小型アセットを分散配置し面的支配を広げる。',
    },
    {
      moveNumber: 4,
      player: 'white',
      kind: 'auto',
      move: { position: 'K', buildType: 'selective', gates: [4, 9] },
      learningPoint: 'WhiteがKにSelective(Gate 4,9)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'K', buildType: 'selective', gates: [4, 9] },
      explanation: 'WhiteはKをSelective(Gate 4,9)で確保し盤面中央下部を押さえる。',
    },
    {
      moveNumber: 5,
      player: 'black',
      kind: 'user',
      move: { position: 'M', buildType: 'selective', gates: [6, 8] },
      learningPoint: 'MをSelective(Gate 6,8)で占有する。',
      shortPrompt: 'MにSelective(Gate 6,8)を指してください。',
      expectedMove: { position: 'M', buildType: 'selective', gates: [6, 8] },
      explanation: 'MはGate 6,8を共有するポジション。SelectiveでGate 6と8の両方に中型アセットを置く。',
    },
    {
      moveNumber: 6,
      player: 'white',
      kind: 'auto',
      move: { position: 'B', buildType: 'massive', gates: [2] },
      learningPoint: 'WhiteがBにMassive(Gate 2)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'B', buildType: 'massive', gates: [2] },
      explanation: 'WhiteはBに着手しGate 2にMassiveを配置する。',
    },
    {
      moveNumber: 7,
      player: 'black',
      kind: 'user',
      move: { position: 'A', buildType: 'massive', gates: [2] },
      learningPoint: 'AにMassive(Gate 2)でGate 2を追加強化する。',
      shortPrompt: 'AにMassive(Gate 2)を指してください。',
      expectedMove: { position: 'A', buildType: 'massive', gates: [2] },
      explanation: 'すでにAを保有しているため再着手。Gate 2にMassive大型アセットを追加し支配を深める。',
    },
    {
      moveNumber: 8,
      player: 'white',
      kind: 'auto',
      move: { position: 'D', buildType: 'selective', gates: [3, 7] },
      learningPoint: 'WhiteがDにSelective(Gate 3,7)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'D', buildType: 'selective', gates: [3, 7] },
      explanation: 'WhiteはDにSelective(Gate 3,7)を置き左上エリアを補強する。',
    },
    {
      moveNumber: 9,
      player: 'black',
      kind: 'user',
      move: { position: 'J', buildType: 'massive', gates: [5] },
      learningPoint: 'JにMassive(Gate 5)で下部を押さえる。',
      shortPrompt: 'JにMassive(Gate 5)を指してください。',
      expectedMove: { position: 'J', buildType: 'massive', gates: [5] },
      explanation: 'JはGate 1,5,7,9に接続。Gate 5にMassiveを置き下側の要所を確保する。',
    },
    {
      moveNumber: 10,
      player: 'white',
      kind: 'auto',
      move: { position: 'C', buildType: 'massive', gates: [4] },
      learningPoint: 'WhiteがCにMassive(Gate 4)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'C', buildType: 'massive', gates: [4] },
      explanation: 'WhiteはCに着手してGate 4にMassiveを置く。',
    },
    {
      moveNumber: 11,
      player: 'black',
      kind: 'auto',
      move: { position: 'G', buildType: 'quad', gates: [1, 4, 7, 10] },
      learningPoint: 'GをQuad(Gate 1,4,7,10)で占有する。',
      shortPrompt: '',
      expectedMove: { position: 'G', buildType: 'quad', gates: [1, 4, 7, 10] },
      explanation: 'GはGate 1,4,7,10の中央交差点。Quadで4Gateに小型アセットを配置し中央支配を固める。',
    },
    {
      moveNumber: 12,
      player: 'white',
      kind: 'auto',
      move: { position: 'K', buildType: 'quad', gates: [4, 9, 10, 11] },
      learningPoint: 'WhiteがKにQuad(Gate 4,9,10,11)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'K', buildType: 'quad', gates: [4, 9, 10, 11] },
      explanation: 'WhiteはKを再びQuadで強化し下部を固める。',
    },
    {
      moveNumber: 13,
      player: 'black',
      kind: 'user',
      move: { position: 'B', buildType: 'massive', gates: [3] },
      learningPoint: 'Position BをCaptureしてMassive(Gate 3)を配置する。',
      shortPrompt: 'BをCaptureしてMassive(Gate 3)を指してください。',
      expectedMove: { position: 'B', buildType: 'massive', gates: [3] },
      capturesBefore: ['B'],
      capturesAfter: ['B'],
      explanation: 'Move 13直前にBlackはPosition BをCapture可能。BをCaptureしてGate 3にMassiveを置くことでポジションBはBlack所有になる。',
      note: 'Move 13直前にPosition BをBlackがCaptureできる想定。Move 13適用後、Position B ownerはBlackになる想定。',
    },
    {
      moveNumber: 14,
      player: 'white',
      kind: 'auto',
      move: { position: 'H', buildType: 'selective', gates: [5, 6] },
      learningPoint: 'WhiteがHにSelective(Gate 5,6)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'H', buildType: 'selective', gates: [5, 6] },
      explanation: 'WhiteはHをSelective(Gate 5,6)で再び強化する。',
    },
    {
      moveNumber: 15,
      player: 'black',
      kind: 'user',
      move: { position: 'H', buildType: 'massive', gates: [5] },
      learningPoint: 'Position HをCaptureしてMassive(Gate 5)を配置する。',
      shortPrompt: 'HをCaptureしてMassive(Gate 5)を指してください。',
      expectedMove: { position: 'H', buildType: 'massive', gates: [5] },
      capturesBefore: ['H'],
      capturesAfter: ['H'],
      explanation: 'Move 15直前にBlackはPosition HをCapture可能。HをCaptureしてGate 5にMassiveを置くことでポジションHはBlack所有になる。',
      note: 'Move 15直前にPosition HをBlackがCaptureできる想定。Move 15適用後、Position H ownerはBlackになる想定。',
    },
    {
      moveNumber: 16,
      player: 'white',
      kind: 'auto',
      move: { position: 'C', buildType: 'massive', gates: [3] },
      learningPoint: 'WhiteがCにMassive(Gate 3)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'C', buildType: 'massive', gates: [3] },
      explanation: 'WhiteはCを再び強化してGate 3にMassiveを置く。',
    },
    {
      moveNumber: 17,
      player: 'black',
      kind: 'auto',
      move: { position: 'F', buildType: 'massive', gates: [11] },
      learningPoint: 'FにMassive(Gate 11)を配置する。',
      shortPrompt: '',
      expectedMove: { position: 'F', buildType: 'massive', gates: [11] },
      explanation: 'BlackはFにMassiveでGate 11を確保する。',
    },
    {
      moveNumber: 18,
      player: 'white',
      kind: 'auto',
      move: { position: 'C', buildType: 'selective', gates: [3, 10] },
      learningPoint: 'WhiteがCにSelective(Gate 3,10)でさらに強化する。',
      shortPrompt: '',
      expectedMove: { position: 'C', buildType: 'selective', gates: [3, 10] },
      explanation: 'WhiteはCにSelective(Gate 3,10)を置き右上を固める。',
    },
    {
      moveNumber: 19,
      player: 'black',
      kind: 'auto',
      move: { position: 'M', buildType: 'massive', gates: [8] },
      learningPoint: 'MにMassive(Gate 8)を追加配置する。',
      shortPrompt: '',
      expectedMove: { position: 'M', buildType: 'massive', gates: [8] },
      explanation: 'BlackはMを再び強化してGate 8にMassiveを追加する。',
    },
    {
      moveNumber: 20,
      player: 'white',
      kind: 'auto',
      move: { position: 'K', buildType: 'massive', gates: [10] },
      learningPoint: 'WhiteがKにMassive(Gate 10)で応じる。',
      shortPrompt: '',
      expectedMove: { position: 'K', buildType: 'massive', gates: [10] },
      explanation: 'WhiteはKを再強化してGate 10にMassiveを置く。',
    },
    {
      moveNumber: 21,
      player: 'black',
      kind: 'user',
      move: { position: 'F', buildType: 'massive', gates: [12] },
      learningPoint: 'FにMassive(Gate 12)を指す。この後勝勢判断を行う。',
      shortPrompt: 'FにMassive(Gate 12)を指してください。',
      expectedMove: { position: 'F', buildType: 'massive', gates: [12] },
      explanation: 'BlackはFをさらに強化しGate 12にMassiveを置く。この手の後Phase 2で勝勢判断questionを表示予定。',
      nextQuestion: '[Phase 2 placeholder] 現在の局面を見て、どちらが有利か判断してください。',
    },
    {
      moveNumber: 22,
      player: 'white',
      kind: 'auto',
      move: { position: 'K', buildType: 'massive', gates: [4] },
      learningPoint: 'WhiteがKにMassive(Gate 4)で最終着手する。',
      shortPrompt: '',
      expectedMove: { position: 'K', buildType: 'massive', gates: [4] },
      explanation: 'WhiteはKにMassive(Gate 4)を置き一局が終盤へ。',
    },
  ],
};
